### ISSUE TITLE
Position carousel arrow to be always in vertical middle of carousel

### ISSUE THREAD

**Issue by peterkos** [codeRIT/brickhack.io#1031]
Currently these are modified manually w/ top margin:
```scss
.carousel .slick-arrow {
        margin-top: 10px;
 }
```

Note the `node_modules/slick-carousel/slick/slick-theme.css` is the original styling those arrows inherit from. Avoid using `!importatnt` when overriding those styles! 

<img width="704" alt="Screen Shot 2020-12-11 at 8 03 11 PM" src="https://user-images.githubusercontent.com/2782749/101968205-e75e4380-3beb-11eb-936c-650f4dee0e69.png">
